sudo: required
services: 
- docker
slim: &slim
      stage: Slim9.9
      os: linux
      language: shell
      script:
        # - license=MATLAB_LICENSE_${MATLAB_VERSION}
        - MATLAB_LICENSE=$MATLAB_LICENSE_R2018b
        - docker-compose -f LNX-docker-compose.yml up --exit-code-from dj
jobs:
  include:
    - <<: *slim
      env:
      - MATLAB_VERSION: R2018b
      - MYSQL_TAG: 5.7-slim9.9
      - DOCKER_CLIENT_TIMEOUT: 120
      - COMPOSE_HTTP_TIMEOUT: 120
